import type { ArtifactContent } from "@/types/artifacts";

/**
 * Transforms an Aria Artifact Content into a list of Google Docs batchUpdate requests.
 */
export function formatArtifactForGoogleDocs(content: ArtifactContent, title: string): any[] {
  const requests: any[] = [];
  
  // A helper to keep track of where we are inserting text
  // Because we insert text at an index, and formatting requires ranges,
  // it's easier to build the text up and then format it, or build requests in reverse.
  // Actually, inserting text at the end (index 1) and pushing things pushes previous text forward.
  // The simplest way to format Google Docs is to insert text from bottom to top, or keep an offset.
  
  // But wait, the Google Docs API allows you to just insert all text, then apply styles if you track lengths.
  // Alternatively, the easiest way to generate a beautiful doc is to build the whole text string,
  // insert it all at once at index 1, and then issue paragraph and text styling commands based on index tracking.

  let currentIndex = 1;
  let fullText = "";
  const styleRequests: any[] = [];

  function appendText(text: string, style?: "TITLE" | "HEADING_1" | "HEADING_2" | "HEADING_3" | "NORMAL", bold = false) {
    const start = currentIndex;
    const length = text.length;
    fullText += text;
    currentIndex += length;

    if (style && style !== "NORMAL") {
      styleRequests.push({
        updateParagraphStyle: {
          range: { startIndex: start, endIndex: currentIndex },
          paragraphStyle: { namedStyleType: style },
          fields: "namedStyleType"
        }
      });
    }

    if (bold) {
      styleRequests.push({
        updateTextStyle: {
          range: { startIndex: start, endIndex: currentIndex },
          textStyle: { bold: true },
          fields: "bold"
        }
      });
    }
  }

  function appendBullet(text: string) {
    const start = currentIndex;
    const formatted = `${text}\n`;
    fullText += formatted;
    currentIndex += formatted.length;
    
    styleRequests.push({
      createParagraphBullets: {
        range: { startIndex: start, endIndex: currentIndex },
        bulletPreset: "BULLET_DISC_CIRCLE_SQUARE"
      }
    });
  }

  // --- Start Building Content ---
  
  // Title
  appendText(`${title}\n`, "TITLE");
  appendText("\n", "NORMAL");

  if (content.meta?.title && content.meta.title !== title) {
    appendText(`${content.meta.title}\n`, "HEADING_2");
    appendText("\n", "NORMAL");
  }

  // Sections
  if (content.sections?.length) {
    for (const section of content.sections) {
      appendText(`${section.title}\n`, "HEADING_1");
      
      if (section.body) {
        appendText(`${section.body}\n`, "NORMAL");
      }
      
      if (section.bullets?.length) {
        for (const bullet of section.bullets) {
          appendBullet(bullet);
        }
        // Extra newline after bullets
        appendText("\n", "NORMAL");
      } else {
        appendText("\n", "NORMAL");
      }
    }
  } else if (content.diagramGraph) {
    appendText("Diagram — view in Aria for interactive version\n", "HEADING_2");
    const nodes = content.diagramGraph.nodes ?? [];
    appendText(`Nodes (${nodes.length}):\n`, "HEADING_3");
    for (const node of nodes) {
      appendBullet(node.data?.label ?? node.id);
    }
  }

  // --- Compile Requests ---
  
  // 1. Insert all text at index 1
  if (fullText.length > 0) {
    requests.push({
      insertText: {
        location: { index: 1 },
        text: fullText
      }
    });
  }

  // 2. Apply styles
  requests.push(...styleRequests);

  return requests;
}

/**
 * Transforms an Aria Artifact Content into Google Sheets batchUpdate rows/columns with formatting.
 */
export function formatArtifactForGoogleSheets(content: ArtifactContent, title: string): { headers: string[]; rows: (string | number)[][] } {
  // Spreadsheet artifact
  if (content.spreadsheetData?.sheets?.[0]) {
    const sheet = content.spreadsheetData.sheets[0];
    return {
      headers: sheet.columns ?? [],
      rows: (sheet.rows ?? []).map((r) => r.map((v) => String(v))),
    };
  }

  // Document sections → convert to two-column table
  if (content.sections?.length) {
    return {
      headers: ["Section", "Content"],
      rows: content.sections.map((s) => [
        s.title,
        [s.body, ...(s.bullets ?? [])].filter(Boolean).join("\n"),
      ]),
    };
  }

  return { headers: ["Field", "Value"], rows: [["Generated by Aria", new Date().toISOString()]] };
}
