import type { AriaConnectorDefinition } from "@/types/aria";

export const ARIA_CONNECTORS: AriaConnectorDefinition[] = [
  {
    id: "google_docs",
    name: "Google Docs",
    category: "documents",
    icon: "📝",
    artifactTypes: ["prd", "brd", "product_brief", "document"],
    sourceType: "google_docs",
    description: "PRDs, briefs, and product documents",
  },
  {
    id: "microsoft_word",
    name: "Microsoft Word",
    category: "documents",
    icon: "📄",
    artifactTypes: ["prd", "brd", "product_brief", "document"],
    sourceType: "microsoft_word",
    description: "Word documents via OneDrive or SharePoint",
  },
  {
    id: "confluence",
    name: "Confluence",
    category: "documents",
    icon: "📘",
    artifactTypes: ["prd", "brd", "document", "decision_log"],
    sourceType: "confluence",
    description: "Team wikis and requirement pages",
  },
  {
    id: "notion",
    name: "Notion",
    category: "documents",
    icon: "📓",
    artifactTypes: ["prd", "product_brief", "meeting_notes", "document"],
    sourceType: "notion",
    description: "Docs, specs, and meeting notes",
  },
  {
    id: "google_sheets",
    name: "Google Sheets",
    category: "spreadsheets",
    icon: "📊",
    artifactTypes: ["data_model", "risk_register"],
    sourceType: "google_sheets",
    description: "Data models and traceability matrices",
  },
  {
    id: "excel",
    name: "Microsoft Excel",
    category: "spreadsheets",
    icon: "📈",
    artifactTypes: ["data_model", "risk_register"],
    sourceType: "excel",
    description: "Spreadsheets via OneDrive or SharePoint",
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "spreadsheets",
    icon: "🗂️",
    artifactTypes: ["data_model", "jira_backlog"],
    sourceType: "mock_connector",
    description: "Structured tables and lightweight backlogs",
  },
  {
    id: "jira",
    name: "Jira",
    category: "delivery",
    icon: "🎫",
    artifactTypes: ["jira_backlog", "epic", "user_story"],
    sourceType: "jira",
    description: "Epics, stories, and delivery tracking",
  },
  {
    id: "linear",
    name: "Linear",
    category: "delivery",
    icon: "◆",
    artifactTypes: ["jira_backlog", "epic", "user_story"],
    sourceType: "linear",
    description: "Issues and sprint planning",
  },
  {
    id: "azure_devops",
    name: "Azure DevOps",
    category: "delivery",
    icon: "🔷",
    artifactTypes: ["jira_backlog", "epic", "user_story", "test_case"],
    sourceType: "mock_connector",
    description: "Work items and test plans",
  },
  {
    id: "figma",
    name: "Figma",
    category: "design",
    icon: "🎨",
    artifactTypes: ["design", "ux_recommendation"],
    sourceType: "figma",
    description: "UX designs and prototypes",
  },
  {
    id: "power_automate",
    name: "Power Automate",
    category: "automation",
    icon: "⚡",
    artifactTypes: ["power_automate_flow", "automation_model"],
    sourceType: "power_automate",
    description: "Workflow automations",
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "automation",
    icon: "🔗",
    artifactTypes: ["power_automate_flow", "automation_model"],
    sourceType: "mock_connector",
    description: "Cross-app automations",
  },
  {
    id: "google_drive",
    name: "Google Drive",
    category: "storage",
    icon: "📁",
    artifactTypes: ["document"],
    sourceType: "google_docs",
    description: "File storage and sharing",
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    category: "storage",
    icon: "🏢",
    artifactTypes: ["sharepoint_list", "document"],
    sourceType: "sharepoint",
    description: "Enterprise document libraries",
  },
  {
    id: "github",
    name: "GitHub",
    category: "engineering",
    icon: "🐙",
    artifactTypes: ["github_repo", "built_app"],
    sourceType: "github",
    description: "Repos, specs, and shipped code",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "engineering",
    icon: "🦊",
    artifactTypes: ["github_repo", "built_app"],
    sourceType: "mock_connector",
    description: "Source control and CI/CD",
  },
];

export function getConnectorById(id: string) {
  return ARIA_CONNECTORS.find((c) => c.id === id);
}

export function getConnectorBySourceType(sourceType: string) {
  return ARIA_CONNECTORS.find((c) => c.sourceType === sourceType);
}
